name: CLITEST 

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilgooz/starport/actions/cli@feat/action
        with:
          args: build --release  -t linux:amd64 -t linux:arm64 -t darwin:amd64 -t darwin:arm64
