name: Release develop 

on:
  push:
    branches:
      - develop 

jobs:
  tag-develop:
    runs-on: ubuntu-latest
    env:
      working-directory: go/src/github.com/tendermint/starport
    
    steps:
      - uses: actions/checkout@v2

      - name: Delete the develop release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: develop 
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: develop
          tag_prefix: ""

      - name: Upsert the develop release
        uses: ncipollo/release-action@v1
        with:
          tag: develop 
          name: develop 
          prerelease: true 

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.working-directory }}
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          workdir: ${{ env.working-directory }}
          version: v0.157.0
          args: release --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
